/**
 * Direkter Test der Bewertungslogik ohne Server/Geocoding/Netzwerk.
 * Simuliert bekannte Testfälle und vergleicht mit Realwerten.
 */
import { buildBewertung } from '../src/bewertung.js';
import type { NormalizedBRW } from '../src/adapters/base.js';
import type { ImmoScoutPrices } from '../src/utils/immoscout-scraper.js';

interface TestCase {
  name: string;
  realwert: number;
  input: Parameters<typeof buildBewertung>;
}

function runTest(tc: TestCase) {
  const result = buildBewertung(...tc.input);
  const abweichung = ((result.realistischer_immobilienwert - tc.realwert) / tc.realwert) * 100;
  const ok = Math.abs(abweichung) <= 20;
  const excellent = Math.abs(abweichung) <= 15;

  console.log(`\n${'='.repeat(70)}`);
  console.log(`TEST: ${tc.name}`);
  console.log(`${'='.repeat(70)}`);
  console.log(`  Realwert:       ${tc.realwert.toLocaleString('de-DE')} €`);
  console.log(`  API-Ergebnis:   ${result.realistischer_immobilienwert.toLocaleString('de-DE')} €`);
  console.log(`  Abweichung:     ${abweichung > 0 ? '+' : ''}${abweichung.toFixed(1)}%`);
  console.log(`  Methode:        ${result.bewertungsmethode}`);
  console.log(`  Konfidenz:      ${result.konfidenz}`);
  console.log(`  Bodenwert:      ${result.bodenwert.toLocaleString('de-DE')} €`);
  console.log(`  Gebäudewert:    ${result.gebaeudewert.toLocaleString('de-DE')} €`);
  console.log(`  Ertragswert:    ${result.ertragswert?.toLocaleString('de-DE') ?? '-'} €`);
  console.log(`  qm-Preis:       ${result.realistischer_qm_preis} €/m²`);
  console.log(`  Spanne:         ${result.immobilienwert_spanne.min.toLocaleString('de-DE')} - ${result.immobilienwert_spanne.max.toLocaleString('de-DE')} €`);
  console.log(`  Faktoren:       ${JSON.stringify(result.faktoren)}`);
  console.log(`  Status:         ${excellent ? '🎯 EXCELLENT' : ok ? '✅ PASS' : '❌ FAIL'} (${excellent ? '≤15%' : ok ? '≤20%' : '>20%'})`);
  console.log(`  Hinweise:`);
  result.hinweise.forEach((h, i) => console.log(`    ${i + 1}. ${h}`));
  console.log(`  Datenquellen:   ${result.datenquellen.join(', ')}`);

  return { ok, abweichung, result };
}

// ─── Testfälle ──────────────────────────────────────────────────────────────

const tests: TestCase[] = [
  {
    name: 'Bramsche EFH (NI) — Realwert 430.000 €',
    realwert: 430000,
    input: [
      // BewertungInput
      {
        art: 'Haus',
        wohnflaeche: 140,
        grundstuecksflaeche: 565,
        baujahr: 2008,
        objektunterart: 'Freistehendes Einfamilienhaus',
        modernisierung: 'Keine Modernisierungen',
        energie: 'Gut',
        ausstattung: 'Gehoben',
      },
      // BRW (offiziell, BORIS-NI)
      {
        wert: 150,
        stichtag: '2025-01-01',
        nutzungsart: 'WA',
        entwicklungszustand: 'B',
        zone: '',
        gemeinde: '',
        bundesland: 'Niedersachsen',
        quelle: 'BORIS-NI (LGLN)',
        lizenz: '© LGLN, dl-de/by-2-0',
        schaetzung: false,
      } satisfies NormalizedBRW,
      // Marktdaten (IS24 Atlas Osnabrück — stadt-level, kein stadtteil)
      {
        stadt: 'osnabrück',
        stadtteil: '', // Kein Stadtteil → Stadt-Durchschnitt
        bundesland: 'niedersachsen',
        haus_kauf_preis: 4986.34,
        haus_kauf_min: 3215.17,
        haus_kauf_max: 6976.19,
        haus_miete_preis: 12.71,
        haus_miete_min: 11.70,
        haus_miete_max: 16.96,
        wohnung_kauf_preis: 3647.17,
        wohnung_kauf_min: 2771.73,
        wohnung_kauf_max: 6639.17,
        wohnung_miete_preis: 11.11,
        wohnung_miete_min: 9.57,
        wohnung_miete_max: 16.34,
        jahr: 2026,
        quartal: 1,
        lat: 52.412,
        lng: 7.971,
      } satisfies ImmoScoutPrices,
      // preisindex
      null,
      // irw
      null,
      // baupreisindex
      null,
      // bundesland
      'Niedersachsen',
    ],
  },
  {
    name: 'Allensbach ETW (BW) — Realwert ~320.000 €',
    realwert: 320000,
    input: [
      {
        art: 'Wohnung',
        wohnflaeche: 86,
        grundstuecksflaeche: 275,
        baujahr: 1963,
        objektunterart: 'Etagenwohnung',
        modernisierung: 'Teilweise modernisiert',
        energie: 'Eher schlecht',
        ausstattung: 'Mittel',
      },
      {
        wert: 1421,
        stichtag: '2026-01-01',
        nutzungsart: 'Wohnbaufläche (geschätzt)',
        entwicklungszustand: 'B',
        zone: 'VVG der Stadt Konstanz',
        gemeinde: 'VVG der Stadt Konstanz',
        bundesland: 'Baden-Württemberg',
        quelle: 'ImmoScout24 Atlas (Schätzwert)',
        lizenz: 'Schätzung basierend auf Marktdaten.',
        schaetzung: true,
      } satisfies NormalizedBRW,
      {
        stadt: 'VVG der Stadt Konstanz',
        stadtteil: '',
        bundesland: 'baden-württemberg',
        haus_kauf_preis: 3465,
        haus_kauf_min: 2268,
        haus_kauf_max: 5393,
        haus_miete_preis: null,
        haus_miete_min: null,
        haus_miete_max: null,
        wohnung_kauf_preis: 4594,
        wohnung_kauf_min: 2690,
        wohnung_kauf_max: 10000,
        wohnung_miete_preis: null,
        wohnung_miete_min: null,
        wohnung_miete_max: null,
        jahr: 2026,
        quartal: 1,
        lat: 47.72,
        lng: 9.06,
      } satisfies ImmoScoutPrices,
      null, null, null,
      'Baden-Württemberg',
    ],
  },
  {
    name: 'Günstiges EFH Sachsen-Anhalt (Magdeburg-Umland) — Realwert ~180.000 €',
    realwert: 180000,
    input: [
      {
        art: 'Haus',
        wohnflaeche: 120,
        grundstuecksflaeche: 600,
        baujahr: 1994,
        objektunterart: 'Freistehendes Einfamilienhaus',
        modernisierung: 'Teilweise modernisiert',
        energie: 'Durchschnittlich',
        ausstattung: 'Mittel',
      },
      {
        wert: 45,
        stichtag: '2025-01-01',
        nutzungsart: 'W',
        entwicklungszustand: 'B',
        zone: '',
        gemeinde: 'Magdeburg',
        bundesland: 'Sachsen-Anhalt',
        quelle: 'BORIS',
        lizenz: 'dl-de/by-2-0',
        schaetzung: false,
      } satisfies NormalizedBRW,
      {
        stadt: 'magdeburg',
        stadtteil: '',
        bundesland: 'sachsen-anhalt',
        haus_kauf_preis: 2200,
        haus_kauf_min: 1400,
        haus_kauf_max: 3500,
        haus_miete_preis: 7.50,
        haus_miete_min: 6.00,
        haus_miete_max: 9.50,
        wohnung_kauf_preis: 1800,
        wohnung_kauf_min: 1100,
        wohnung_kauf_max: 3000,
        wohnung_miete_preis: 7.00,
        wohnung_miete_min: 5.50,
        wohnung_miete_max: 9.00,
        jahr: 2026,
        quartal: 1,
        lat: 52.13,
        lng: 11.63,
      } satisfies ImmoScoutPrices,
      null, null, null,
      'Sachsen-Anhalt',
    ],
  },
  {
    name: 'Hamburg Stadtvilla (Premium A-Lage) — Realwert ~1.200.000 €',
    realwert: 1200000,
    input: [
      {
        art: 'Haus',
        wohnflaeche: 180,
        grundstuecksflaeche: 450,
        baujahr: 2015,
        objektunterart: 'Freistehendes Einfamilienhaus',
        modernisierung: null,
        energie: 'Sehr gut',
        ausstattung: 'Stark gehoben',
      },
      {
        wert: 800,
        stichtag: '2025-01-01',
        nutzungsart: 'W',
        entwicklungszustand: 'B',
        zone: 'Blankenese',
        gemeinde: 'Hamburg',
        bundesland: 'Hamburg',
        quelle: 'GAG Hamburg',
        lizenz: 'dl-de/by-2-0',
        schaetzung: false,
      } satisfies NormalizedBRW,
      {
        stadt: 'hamburg',
        stadtteil: 'blankenese',
        bundesland: 'hamburg',
        haus_kauf_preis: 6500,
        haus_kauf_min: 4500,
        haus_kauf_max: 9000,
        haus_miete_preis: 16.00,
        haus_miete_min: 13.00,
        haus_miete_max: 20.00,
        wohnung_kauf_preis: 5800,
        wohnung_kauf_min: 4000,
        wohnung_kauf_max: 8500,
        wohnung_miete_preis: 14.00,
        wohnung_miete_min: 11.00,
        wohnung_miete_max: 18.00,
        jahr: 2026,
        quartal: 1,
        lat: 53.56,
        lng: 9.80,
      } satisfies ImmoScoutPrices,
      null, null, null,
      'Hamburg',
    ],
  },
  {
    name: 'EFH nur mit BRW (kein IS24) — NHK-only Test',
    realwert: 280000, // NRW-Durchschnitt: 2200 €/m² × 130m² × 0.96 ≈ 275k
    input: [
      {
        art: 'Haus',
        wohnflaeche: 130,
        grundstuecksflaeche: 500,
        baujahr: 2000,
        objektunterart: 'Freistehendes Einfamilienhaus',
        modernisierung: null,
        energie: null,
        ausstattung: 'Mittel',
      },
      {
        wert: 120,
        stichtag: '2025-01-01',
        nutzungsart: 'W',
        entwicklungszustand: 'B',
        zone: '',
        gemeinde: '',
        bundesland: 'Nordrhein-Westfalen',
        quelle: 'BORIS-NRW',
        lizenz: 'dl-de/by-2-0',
        schaetzung: false,
      } satisfies NormalizedBRW,
      // Kein IS24 Marktdaten
      null,
      null, null, null,
      'Nordrhein-Westfalen',
    ],
  },

  // ─── Neue Testfälle (erweiterte Referenz-Suite) ──────────────────────────

  {
    name: 'Baesweiler DHH (NRW) — Gutachten 305.000 € [HAUPTREFERENZ]',
    realwert: 305000,
    input: [
      {
        art: 'Haus',
        wohnflaeche: 117,
        grundstuecksflaeche: 345,
        baujahr: 1986,
        objektunterart: 'Doppelhaushälfte',
        modernisierung: 'Keine Modernisierungen',
        energie: '3',
        ausstattung: 'Mittel',
      },
      {
        wert: 260,
        stichtag: '2026-01-01',
        nutzungsart: 'W',
        entwicklungszustand: 'B',
        zone: '',
        gemeinde: 'Baesweiler',
        bundesland: 'Nordrhein-Westfalen',
        quelle: 'BORIS-NRW',
        lizenz: 'Datenlizenz Deutschland – Zero – Version 2.0',
        schaetzung: false,
      } satisfies NormalizedBRW,
      {
        stadt: 'aachen',
        stadtteil: '',
        bundesland: 'nordrhein-westfalen',
        haus_kauf_preis: 4012.55,
        haus_kauf_min: 3517.41,
        haus_kauf_max: 5854.72,
        haus_miete_preis: 13.27,
        haus_miete_min: 13.20,
        haus_miete_max: 18.69,
        wohnung_kauf_preis: 3935.57,
        wohnung_kauf_min: 3487.04,
        wohnung_kauf_max: 6204.14,
        wohnung_miete_preis: 11.40,
        wohnung_miete_min: 10.82,
        wohnung_miete_max: 17.97,
        jahr: 2026,
        quartal: 1,
        lat: 50.91,
        lng: 6.18,
      } satisfies ImmoScoutPrices,
      null, null, null,
      'Nordrhein-Westfalen',
    ],
  },
  {
    name: 'Altbau EFH pre-1950 (Berlin, A-Lage) — Realwert ~420.000 €',
    realwert: 420000,
    input: [
      {
        art: 'Haus',
        wohnflaeche: 150,
        grundstuecksflaeche: 400,
        baujahr: 1935,
        objektunterart: 'Freistehendes Einfamilienhaus',
        modernisierung: 'Teilweise modernisiert',
        energie: 'Eher schlecht',
        ausstattung: 'Mittel',
      },
      {
        wert: 450,
        stichtag: '2025-01-01',
        nutzungsart: 'W',
        entwicklungszustand: 'B',
        zone: '',
        gemeinde: 'Berlin',
        bundesland: 'Berlin',
        quelle: 'BORIS-BE',
        lizenz: 'dl-de/by-2-0',
        schaetzung: false,
      } satisfies NormalizedBRW,
      {
        stadt: 'berlin',
        stadtteil: '',
        bundesland: 'berlin',
        haus_kauf_preis: 4800,
        haus_kauf_min: 3200,
        haus_kauf_max: 7500,
        haus_miete_preis: 14.00,
        haus_miete_min: 11.00,
        haus_miete_max: 18.00,
        wohnung_kauf_preis: 4500,
        wohnung_kauf_min: 3000,
        wohnung_kauf_max: 7000,
        wohnung_miete_preis: 12.50,
        wohnung_miete_min: 9.50,
        wohnung_miete_max: 16.00,
        jahr: 2026,
        quartal: 1,
        lat: 52.52,
        lng: 13.40,
      } satisfies ImmoScoutPrices,
      null, null, null,
      'Berlin',
    ],
  },
  {
    name: 'Neubau DHH (Bayern, BJ 2022) — Realwert ~480.000 €',
    realwert: 480000,
    input: [
      {
        art: 'Haus',
        wohnflaeche: 130,
        grundstuecksflaeche: 300,
        baujahr: 2022,
        objektunterart: 'Doppelhaushälfte',
        modernisierung: null,
        energie: 'Sehr gut',
        ausstattung: 'Gehoben',
      },
      {
        wert: 250,
        stichtag: '2025-01-01',
        nutzungsart: 'WA',
        entwicklungszustand: 'B',
        zone: '',
        gemeinde: 'Augsburg',
        bundesland: 'Bayern',
        quelle: 'BORIS-BY',
        lizenz: 'dl-de/by-2-0',
        schaetzung: false,
      } satisfies NormalizedBRW,
      {
        stadt: 'augsburg',
        stadtteil: '',
        bundesland: 'bayern',
        haus_kauf_preis: 4200,
        haus_kauf_min: 3000,
        haus_kauf_max: 6500,
        haus_miete_preis: 13.50,
        haus_miete_min: 11.00,
        haus_miete_max: 17.00,
        wohnung_kauf_preis: 4000,
        wohnung_kauf_min: 2800,
        wohnung_kauf_max: 6000,
        wohnung_miete_preis: 12.00,
        wohnung_miete_min: 9.50,
        wohnung_miete_max: 15.00,
        jahr: 2026,
        quartal: 1,
        lat: 48.37,
        lng: 10.90,
      } satisfies ImmoScoutPrices,
      null, null, null,
      'Bayern',
    ],
  },
  {
    name: 'C-Lage Reihenmittelhaus (Thüringen) — Realwert ~80.000 €',
    realwert: 80000,
    input: [
      {
        art: 'Haus',
        wohnflaeche: 100,
        grundstuecksflaeche: 250,
        baujahr: 1975,
        objektunterart: 'Reihenmittelhaus',
        modernisierung: 'Einzelne Maßnahmen',
        energie: 'Eher schlecht',
        ausstattung: 'Einfach',
      },
      {
        wert: 35,
        stichtag: '2025-01-01',
        nutzungsart: 'W',
        entwicklungszustand: 'B',
        zone: '',
        gemeinde: 'Gera',
        bundesland: 'Thüringen',
        quelle: 'BORIS',
        lizenz: 'dl-de/by-2-0',
        schaetzung: false,
      } satisfies NormalizedBRW,
      {
        stadt: 'gera',
        stadtteil: '',
        bundesland: 'thüringen',
        haus_kauf_preis: 1500,
        haus_kauf_min: 900,
        haus_kauf_max: 2500,
        haus_miete_preis: 6.50,
        haus_miete_min: 5.00,
        haus_miete_max: 8.50,
        wohnung_kauf_preis: 1200,
        wohnung_kauf_min: 700,
        wohnung_kauf_max: 2000,
        wohnung_miete_preis: 5.50,
        wohnung_miete_min: 4.50,
        wohnung_miete_max: 7.50,
        jahr: 2026,
        quartal: 1,
        lat: 50.88,
        lng: 12.08,
      } satisfies ImmoScoutPrices,
      null, null, null,
      'Thüringen',
    ],
  },
  {
    name: 'ETW München (A-Lage) — Realwert ~400.000 €',
    realwert: 400000,
    input: [
      {
        art: 'Wohnung',
        wohnflaeche: 65,
        grundstuecksflaeche: null,
        baujahr: 1998,
        objektunterart: 'Etagenwohnung',
        modernisierung: 'Umfassend modernisiert',
        energie: 'Gut',
        ausstattung: 'Gehoben',
      },
      {
        wert: 2500,
        stichtag: '2025-01-01',
        nutzungsart: 'W',
        entwicklungszustand: 'B',
        zone: '',
        gemeinde: 'München',
        bundesland: 'Bayern',
        quelle: 'BORIS-BY',
        lizenz: 'dl-de/by-2-0',
        schaetzung: false,
      } satisfies NormalizedBRW,
      {
        stadt: 'münchen',
        stadtteil: '',
        bundesland: 'bayern',
        haus_kauf_preis: 8500,
        haus_kauf_min: 6000,
        haus_kauf_max: 12000,
        haus_miete_preis: 18.00,
        haus_miete_min: 14.00,
        haus_miete_max: 24.00,
        wohnung_kauf_preis: 7200,
        wohnung_kauf_min: 5000,
        wohnung_kauf_max: 11000,
        wohnung_miete_preis: 16.00,
        wohnung_miete_min: 12.00,
        wohnung_miete_max: 22.00,
        jahr: 2026,
        quartal: 1,
        lat: 48.14,
        lng: 11.58,
      } satisfies ImmoScoutPrices,
      null, null, null,
      'Bayern',
    ],
  },
  {
    name: 'ZFH Rheinland-Pfalz (Mainz-Umland) — Realwert ~380.000 €',
    realwert: 380000,
    input: [
      {
        art: 'Haus',
        wohnflaeche: 180,
        grundstuecksflaeche: 500,
        baujahr: 1988,
        objektunterart: 'Zweifamilienhaus',
        modernisierung: '3', // Teilweise (numerisch)
        energie: '3',
        ausstattung: 'Mittel',
      },
      {
        wert: 180,
        stichtag: '2025-01-01',
        nutzungsart: 'W',
        entwicklungszustand: 'B',
        zone: '',
        gemeinde: 'Ingelheim am Rhein',
        bundesland: 'Rheinland-Pfalz',
        quelle: 'BORIS-RP',
        lizenz: 'dl-de/by-2-0',
        schaetzung: false,
      } satisfies NormalizedBRW,
      {
        stadt: 'mainz',
        stadtteil: '',
        bundesland: 'rheinland-pfalz',
        haus_kauf_preis: 3800,
        haus_kauf_min: 2500,
        haus_kauf_max: 5800,
        haus_miete_preis: 11.50,
        haus_miete_min: 9.50,
        haus_miete_max: 15.00,
        wohnung_kauf_preis: 3500,
        wohnung_kauf_min: 2300,
        wohnung_kauf_max: 5200,
        wohnung_miete_preis: 10.50,
        wohnung_miete_min: 8.50,
        wohnung_miete_max: 14.00,
        jahr: 2026,
        quartal: 1,
        lat: 50.00,
        lng: 8.27,
      } satisfies ImmoScoutPrices,
      null, null, null,
      'Rheinland-Pfalz',
    ],
  },
  {
    name: 'Reihenendhaus NRW (Köln-Umland) — Realwert ~350.000 €',
    realwert: 350000,
    input: [
      {
        art: 'Haus',
        wohnflaeche: 110,
        grundstuecksflaeche: 250,
        baujahr: 2005,
        objektunterart: 'Reihenendhaus',
        modernisierung: null,
        energie: 'Gut',
        ausstattung: 'Mittel',
      },
      {
        wert: 300,
        stichtag: '2025-01-01',
        nutzungsart: 'WA',
        entwicklungszustand: 'B',
        zone: '',
        gemeinde: 'Bergisch Gladbach',
        bundesland: 'Nordrhein-Westfalen',
        quelle: 'BORIS-NRW',
        lizenz: 'dl-de/by-2-0',
        schaetzung: false,
      } satisfies NormalizedBRW,
      {
        stadt: 'köln',
        stadtteil: '',
        bundesland: 'nordrhein-westfalen',
        haus_kauf_preis: 4300,
        haus_kauf_min: 3000,
        haus_kauf_max: 6500,
        haus_miete_preis: 13.00,
        haus_miete_min: 10.50,
        haus_miete_max: 17.00,
        wohnung_kauf_preis: 3800,
        wohnung_kauf_min: 2700,
        wohnung_kauf_max: 5800,
        wohnung_miete_preis: 11.80,
        wohnung_miete_min: 9.50,
        wohnung_miete_max: 15.50,
        jahr: 2026,
        quartal: 1,
        lat: 50.94,
        lng: 6.96,
      } satisfies ImmoScoutPrices,
      null, null, null,
      'Nordrhein-Westfalen',
    ],
  },
  {
    name: 'Bungalow Schleswig-Holstein (Lübeck-Umland) — Realwert ~260.000 €',
    realwert: 260000,
    input: [
      {
        art: 'Haus',
        wohnflaeche: 120,
        grundstuecksflaeche: 700,
        baujahr: 1978,
        objektunterart: 'Bungalow',
        modernisierung: 'Teilweise modernisiert',
        energie: 'Durchschnittlich',
        ausstattung: 'Mittel',
      },
      {
        wert: 120,
        stichtag: '2025-01-01',
        nutzungsart: 'W',
        entwicklungszustand: 'B',
        zone: '',
        gemeinde: 'Lübeck',
        bundesland: 'Schleswig-Holstein',
        quelle: 'BORIS-SH',
        lizenz: 'dl-de/by-2-0',
        schaetzung: false,
      } satisfies NormalizedBRW,
      {
        stadt: 'lübeck',
        stadtteil: '',
        bundesland: 'schleswig-holstein',
        haus_kauf_preis: 3200,
        haus_kauf_min: 2200,
        haus_kauf_max: 5000,
        haus_miete_preis: 11.00,
        haus_miete_min: 9.00,
        haus_miete_max: 14.00,
        wohnung_kauf_preis: 2800,
        wohnung_kauf_min: 2000,
        wohnung_kauf_max: 4500,
        wohnung_miete_preis: 9.50,
        wohnung_miete_min: 8.00,
        wohnung_miete_max: 12.50,
        jahr: 2026,
        quartal: 1,
        lat: 53.87,
        lng: 10.69,
      } satisfies ImmoScoutPrices,
      null, null, null,
      'Schleswig-Holstein',
    ],
  },
  {
    name: 'Fallback ohne IS24 und ohne BRW — Bundesdurchschnitt',
    realwert: 220000, // Hessen Landesdurchschnitt: 2800 €/m² × 100m² × ~0.8 ≈ 224k
    input: [
      {
        art: 'Haus',
        wohnflaeche: 100,
        grundstuecksflaeche: 400,
        baujahr: 1990,
        objektunterart: 'Freistehendes Einfamilienhaus',
        modernisierung: null,
        energie: null,
        ausstattung: 'Mittel',
      },
      // Kein BRW
      null,
      // Kein IS24
      null,
      null, null, null,
      'Hessen',
    ],
  },
  {
    name: 'ETW Frankfurt (Hessen) — Realwert ~280.000 €',
    realwert: 280000,
    input: [
      {
        art: 'Wohnung',
        wohnflaeche: 70,
        grundstuecksflaeche: null,
        baujahr: 2010,
        objektunterart: 'Etagenwohnung',
        modernisierung: null,
        energie: 'Gut',
        ausstattung: 'Mittel',
      },
      {
        wert: 1800,
        stichtag: '2025-01-01',
        nutzungsart: 'W',
        entwicklungszustand: 'B',
        zone: '',
        gemeinde: 'Frankfurt am Main',
        bundesland: 'Hessen',
        quelle: 'BORIS-HE',
        lizenz: 'dl-de/by-2-0',
        schaetzung: false,
      } satisfies NormalizedBRW,
      {
        stadt: 'frankfurt-am-main',
        stadtteil: '',
        bundesland: 'hessen',
        haus_kauf_preis: 5200,
        haus_kauf_min: 3500,
        haus_kauf_max: 8000,
        haus_miete_preis: 15.00,
        haus_miete_min: 12.00,
        haus_miete_max: 20.00,
        wohnung_kauf_preis: 4800,
        wohnung_kauf_min: 3200,
        wohnung_kauf_max: 7500,
        wohnung_miete_preis: 13.50,
        wohnung_miete_min: 10.50,
        wohnung_miete_max: 18.00,
        jahr: 2026,
        quartal: 1,
        lat: 50.11,
        lng: 8.68,
      } satisfies ImmoScoutPrices,
      null, null, null,
      'Hessen',
    ],
  },
];

// ─── Tests ausführen ────────────────────────────────────────────────────────

console.log('╔══════════════════════════════════════════════════════════════════╗');
console.log('║         BEWERTUNG QUALITÄTSTEST — Plausibilitätsprüfung         ║');
console.log('╚══════════════════════════════════════════════════════════════════╝');

let excellent = 0;
let passed = 0;
let failed = 0;

for (const tc of tests) {
  const { ok, abweichung } = runTest(tc);
  if (Math.abs(abweichung) <= 15) excellent++;
  if (ok) passed++;
  else failed++;
}

console.log(`\n${'═'.repeat(70)}`);
console.log(`ERGEBNIS: ${passed}/${tests.length} bestanden (≤20%), ${excellent}/${tests.length} exzellent (≤15%), ${failed} fehlgeschlagen`);
console.log(`${'═'.repeat(70)}`);

process.exit(failed > 0 ? 1 : 0);
